<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <Deterministic>true</Deterministic>
    <PathMap>$(MSBuildProjectDirectory)=/_/src/MagicMouse.Core</PathMap>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
